# Generated by Django 5.2.1 on 2025-06-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0004_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
