# Generated by Django 5.2.1 on 2025-06-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='curious_count',
            field=models.IntegerField(default=0),
        ),
    ]
