# Generated by Django 5.2.1 on 2025-06-17 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0012_alter_questionview_viewed_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionview',
            unique_together=set(),
        ),
    ]
