# Generated by Django 5.2.1 on 2025-06-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0013_alter_questionview_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_adopted',
            field=models.BooleanField(default=False),
        ),
    ]
