# Generated by Django 5.2.1 on 2025-06-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0015_concern'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='neutral_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='unhelpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
