# Generated by Django 5.2.1 on 2025-06-23 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_userprofile_exp'),
        ('mentor', '0016_answer_helpful_count_answer_neutral_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('helpful', '유용해요'), ('neutral', '애매해요'), ('unhelpful', '도움 안 됐어요')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor.answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
            options={
                'unique_together': {('user', 'answer')},
            },
        ),
    ]
