# Generated by Django 5.2.1 on 2025-06-26 04:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0018_alter_answervote_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='helpful_count',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='neutral_count',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='unhelpful_count',
        ),
        migrations.AddField(
            model_name='answer',
            name='bad_users',
            field=models.ManyToManyField(blank=True, related_name='bad_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='good_users',
            field=models.ManyToManyField(blank=True, related_name='good_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='soso_users',
            field=models.ManyToManyField(blank=True, related_name='soso_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AnswerVote',
        ),
    ]
