# Generated by Django 5.2.1 on 2025-06-10 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('student', '대학생'), ('worker', '직장인'), ('jobseeker', '백수'), ('selfliving', '자취생'), ('other', '기타')], max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('interests', models.TextField(blank=True)),
                ('keywords', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
