# Generated by Django 5.2.1 on 2025-06-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='region',
            field=models.CharField(blank=True, choices=[('seoul', '서울'), ('gyeonggi', '경기도'), ('busan', '부산'), ('jeonbuk', '전라북도'), ('other', '기타')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('mentor', '멘토'), ('mentee', '멘티'), ('both', '둘다')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('student', '대학생'), ('worker', '직장인'), ('jobseeker', '취준생'), ('selfliving', '자취생'), ('other', '기타')], max_length=20),
        ),
    ]
