# Generated by Django 5.2.1 on 2025-06-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='region',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_type',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='keywords',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(default='시언', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='디', max_length=100),
            preserve_default=False,
        ),
    ]
