# Generated by Django 5.2.1 on 2025-06-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_job_userprofile_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_edit_count',
            field=models.IntegerField(default=0),
        ),
    ]
