# Generated by Django 5.2.1 on 2025-06-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_lifeevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age_range',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
