# Generated by Django 5.2.1 on 2025-06-26 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_userprofile_exp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='exp',
        ),
    ]
