# Generated by Django 5.1.7 on 2025-07-02 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_userprofile_badge_remove_userprofile_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
