# Generated by Django 5.2.1 on 2025-07-03 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_userprofile_nickname'),
        ('youth_policy', '0051_rename_name_youthpolicy_정책명_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='youth_policy.sido'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sigungu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='youth_policy.sigungu'),
        ),
    ]
