# Generated by Django 5.2.1 on 2025-06-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouthPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='정책명')),
                ('description', models.TextField(verbose_name='정책설명')),
                ('age_range', models.CharField(max_length=50, verbose_name='대상연령')),
                ('keyword', models.CharField(blank=True, max_length=100, verbose_name='정책키워드')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='시행지역')),
            ],
        ),
    ]
