# Generated by Django 5.2.1 on 2025-06-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0002_youthpolicy_finish_youthpolicy_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youthpolicy',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='youthpolicy',
            name='start',
        ),
        migrations.AddField(
            model_name='youthpolicy',
            name='URL_ADD',
            field=models.CharField(blank=True, max_length=100, verbose_name='신청URL'),
        ),
        migrations.AddField(
            model_name='youthpolicy',
            name='period',
            field=models.CharField(blank=True, max_length=100, verbose_name='신청기간'),
        ),
    ]
