# Generated by Django 5.2.1 on 2025-06-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0003_remove_youthpolicy_finish_remove_youthpolicy_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youthpolicy',
            name='URL_ADD',
            field=models.URLField(blank=True, max_length=100, verbose_name='신청URL'),
        ),
    ]
