# Generated by Django 5.2.1 on 2025-06-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0004_alter_youthpolicy_url_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youthpolicy',
            name='URL_ADD',
            field=models.URLField(blank=True, verbose_name='신청URL'),
        ),
        migrations.AlterField(
            model_name='youthpolicy',
            name='period',
            field=models.CharField(blank=True, max_length=200, verbose_name='신청기간'),
        ),
        migrations.AlterField(
            model_name='youthpolicy',
            name='region',
            field=models.CharField(blank=True, max_length=200, verbose_name='시행지역'),
        ),
    ]
