# Generated by Django 5.2.1 on 2025-06-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0005_alter_youthpolicy_url_add_alter_youthpolicy_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youthpolicy',
            name='addaply',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='youthpolicy',
            name='document',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='youthpolicy',
            name='etc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='youthpolicy',
            name='major',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='youthpolicy',
            name='maxage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youthpolicy',
            name='medium',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='youthpolicy',
            name='minage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
