# Generated by Django 5.2.1 on 2025-06-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0006_youthpolicy_addaply_youthpolicy_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youthpolicy',
            name='addaply',
            field=models.TextField(blank=True, verbose_name='추가신청자격조건내용'),
        ),
        migrations.AlterField(
            model_name='youthpolicy',
            name='document',
            field=models.TextField(blank=True, verbose_name='제출서류내용'),
        ),
        migrations.AlterField(
            model_name='youthpolicy',
            name='etc',
            field=models.TextField(blank=True, verbose_name='기타사항내용'),
        ),
        migrations.AlterField(
            model_name='youthpolicy',
            name='major',
            field=models.CharField(blank=True, max_length=100, verbose_name='대분류명'),
        ),
        migrations.AlterField(
            model_name='youthpolicy',
            name='maxage',
            field=models.IntegerField(blank=True, null=True, verbose_name='최대연령'),
        ),
        migrations.AlterField(
            model_name='youthpolicy',
            name='medium',
            field=models.CharField(blank=True, max_length=100, verbose_name='중분류명'),
        ),
        migrations.AlterField(
            model_name='youthpolicy',
            name='minage',
            field=models.IntegerField(blank=True, null=True, verbose_name='최소연령'),
        ),
    ]
