# Generated by Django 5.2.1 on 2025-06-09 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0009_youthpolicy_created_at_youthpolicy_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youthpolicy',
            name='created_at',
        ),
    ]
