# Generated by Django 5.2.1 on 2025-06-09 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0011_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='sido',
            new_name='code',
        ),
    ]
