# Generated by Django 5.2.1 on 2025-06-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0012_rename_sido_region_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(),
        ),
    ]
