# Generated by Django 5.2.1 on 2025-06-09 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0013_alter_region_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='updated_at',
        ),
    ]
