# Generated by Django 5.2.1 on 2025-06-09 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0014_remove_region_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sigungu',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('sido_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='youthpolicy',
            name='sigungu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='youth_policy.sigungu'),
        ),
    ]
