# Generated by Django 5.2.1 on 2025-06-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0016_remove_region_id_alter_region_code_alter_region_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sido',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
