# Generated by Django 5.2.1 on 2025-06-10 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0017_sido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youthpolicy',
            name='sigungu',
        ),
        migrations.DeleteModel(
            name='Sigungu',
        ),
    ]
