# Generated by Django 5.2.1 on 2025-06-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0019_sigungu_youthpolicy_sigungu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youthpolicy',
            name='URL_ADD',
        ),
        migrations.RemoveField(
            model_name='youthpolicy',
            name='addaply',
        ),
        migrations.RemoveField(
            model_name='youthpolicy',
            name='age_range',
        ),
        migrations.RemoveField(
            model_name='youthpolicy',
            name='description',
        ),
        migrations.RemoveField(
            model_name='youthpolicy',
            name='document',
        ),
        migrations.RemoveField(
            model_name='youthpolicy',
            name='etc',
        ),
        migrations.RemoveField(
            model_name='youthpolicy',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='youthpolicy',
            name='major',
        ),
        migrations.RemoveField(
            model_name='youthpolicy',
            name='maxage',
        ),
        migrations.RemoveField(
            model_name='youthpolicy',
            name='medium',
        ),
        migrations.RemoveField(
            model_name='youthpolicy',
            name='minage',
        ),
        migrations.RemoveField(
            model_name='youthpolicy',
            name='name',
        ),
        migrations.RemoveField(
            model_name='youthpolicy',
            name='period',
        ),
        migrations.RemoveField(
            model_name='youthpolicy',
            name='region',
        ),
        migrations.AddField(
            model_name='youthpolicy',
            name='대상연령',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='youthpolicy',
            name='시행지역',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='youthpolicy',
            name='신청URL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youthpolicy',
            name='신청기간',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='youthpolicy',
            name='정책명',
            field=models.CharField(default='데이터 변경', max_length=255),
        ),
        migrations.AddField(
            model_name='youthpolicy',
            name='정책설명',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youthpolicy',
            name='정책키워드',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='youthpolicy',
            name='제출서류내용',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youthpolicy',
            name='참여제외대상',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youthpolicy',
            name='추가신청자격조건내용',
            field=models.TextField(blank=True, null=True),
        ),
    ]
