# Generated by Django 5.2.1 on 2025-06-12 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0020_remove_youthpolicy_url_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youthpolicy',
            name='sigungu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='youth_policy.sido'),
        ),
    ]
