# Generated by Django 5.2.1 on 2025-06-12 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0021_alter_youthpolicy_sigungu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youthpolicy',
            old_name='sigungu',
            new_name='sido',
        ),
    ]
