# Generated by Django 5.2.1 on 2025-06-12 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0022_rename_sigungu_youthpolicy_sido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youthpolicy',
            name='sido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youth_policy.sido'),
        ),
    ]
