# Generated by Django 5.2.1 on 2025-06-12 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0024_remove_youthpolicy_sido_youthpolicy_sigungu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youthpolicy',
            name='sigungu',
        ),
        migrations.AddField(
            model_name='youthpolicy',
            name='sido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youth_policy.sido'),
        ),
    ]
