# Generated by Django 5.2.1 on 2025-06-12 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0025_remove_youthpolicy_sigungu_youthpolicy_sido'),
    ]

    operations = [
        migrations.AddField(
            model_name='youthpolicy',
            name='sigungu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youth_policy.sigungu'),
        ),
    ]
