# Generated by Django 5.2.1 on 2025-06-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0026_youthpolicy_sigungu'),
    ]

    operations = [
        migrations.AddField(
            model_name='youthpolicy',
            name='생애주기단계',
            field=models.TextField(blank=True, null=True),
        ),
    ]
