# Generated by Django 5.2.1 on 2025-06-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0028_policyviewlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='youthpolicy',
            name='relation_with',
            field=models.ManyToManyField(blank=True, related_name='추천된_정책들', to='youth_policy.youthpolicy'),
        ),
    ]
