# Generated by Django 5.2.1 on 2025-06-16 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0029_youthpolicy_relation_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='youthpolicy',
            name='curation_comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='youthpolicy',
            name='is_curated',
            field=models.BooleanField(default=False),
        ),
    ]
