# Generated by Django 5.2.1 on 2025-06-16 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0030_youthpolicy_curation_comment_youthpolicy_is_curated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youthpolicy',
            old_name='is_curated',
            new_name='is_weekly_pick',
        ),
        migrations.RemoveField(
            model_name='youthpolicy',
            name='curation_comment',
        ),
    ]
