# Generated by Django 5.2.1 on 2025-06-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0031_rename_is_curated_youthpolicy_is_weekly_pick_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youthpolicy',
            name='weekly_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
