# Generated by Django 5.2.1 on 2025-06-18 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0032_youthpolicy_weekly_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youthpolicy',
            name='weekly_comment',
        ),
    ]
