# Generated by Django 5.2.1 on 2025-06-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0033_remove_youthpolicy_weekly_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='youthpolicy',
            name='weekly_comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
