# Generated by Django 5.2.1 on 2025-06-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0034_youthpolicy_weekly_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='youthpolicy',
            name='정책설명요약',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
