# Generated by Django 5.2.1 on 2025-06-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0035_youthpolicy_정책설명요약'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youthpolicy',
            name='정책설명요약',
            field=models.TextField(blank=True, null=True),
        ),
    ]
