# Generated by Django 5.2.1 on 2025-06-20 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0036_alter_youthpolicy_정책설명요약'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youthpolicy',
            name='relation_with',
        ),
    ]
