# Generated by Django 5.2.1 on 2025-06-20 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0037_remove_youthpolicy_relation_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youthpolicy',
            name='is_weekly_pick',
        ),
        migrations.RemoveField(
            model_name='youthpolicy',
            name='weekly_comment',
        ),
    ]
