# Generated by Django 5.2.1 on 2025-06-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0038_remove_youthpolicy_is_weekly_pick_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youthpolicy',
            name='신청기간',
        ),
        migrations.AddField(
            model_name='youthpolicy',
            name='application_end',
            field=models.DateField(blank=True, null=True, verbose_name='신청 마감일'),
        ),
        migrations.AddField(
            model_name='youthpolicy',
            name='application_period',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='신청기간'),
        ),
        migrations.AddField(
            model_name='youthpolicy',
            name='application_start',
            field=models.DateField(blank=True, null=True, verbose_name='신청 시작일'),
        ),
    ]
