# Generated by Django 5.2.1 on 2025-06-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0039_remove_youthpolicy_신청기간_youthpolicy_application_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youthpolicy',
            name='시행지역',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
