# Generated by Django 5.2.1 on 2025-06-25 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0040_alter_youthpolicy_시행지역'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PolicyViewLog',
        ),
    ]
