# Generated by Django 5.2.1 on 2025-06-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0041_delete_policyviewlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youthpolicy',
            name='정책키워드',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
