# Generated by Django 5.2.1 on 2025-06-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0043_alter_youthpolicy_시행지역'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youthpolicy',
            name='sido',
        ),
        migrations.AddField(
            model_name='youthpolicy',
            name='sido',
            field=models.ManyToManyField(blank=True, to='youth_policy.sido'),
        ),
    ]
