# Generated by Django 5.2.1 on 2025-06-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0045_remove_youthpolicy_sido_youthpolicy_sido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youthpolicy',
            name='sido',
        ),
        migrations.RemoveField(
            model_name='youthpolicy',
            name='sigungu',
        ),
        migrations.AddField(
            model_name='youthpolicy',
            name='sido',
            field=models.ManyToManyField(blank=True, to='youth_policy.sido'),
        ),
        migrations.AddField(
            model_name='youthpolicy',
            name='sigungu',
            field=models.ManyToManyField(blank=True, to='youth_policy.sigungu'),
        ),
    ]
