# Generated by Django 5.2.1 on 2025-06-26 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0046_remove_youthpolicy_sido_remove_youthpolicy_sigungu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youthpolicy',
            name='sido',
        ),
        migrations.RemoveField(
            model_name='youthpolicy',
            name='sigungu',
        ),
        migrations.AddField(
            model_name='youthpolicy',
            name='sido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youth_policy.sido'),
        ),
        migrations.AddField(
            model_name='youthpolicy',
            name='sigungu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youth_policy.sigungu'),
        ),
    ]
