# Generated by Django 5.2.1 on 2025-06-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0047_remove_youthpolicy_sido_remove_youthpolicy_sigungu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youthpolicy',
            name='sigungu',
        ),
        migrations.AddField(
            model_name='youthpolicy',
            name='sigungu',
            field=models.ManyToManyField(blank=True, to='youth_policy.sigungu'),
        ),
    ]
