# Generated by Django 5.2.1 on 2025-07-03 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0048_remove_youthpolicy_sigungu_youthpolicy_sigungu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youthpolicy',
            old_name='제출서류내용',
            new_name='document',
        ),
    ]
