# Generated by Django 5.2.1 on 2025-07-03 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0049_rename_제출서류내용_youthpolicy_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youthpolicy',
            old_name='정책명',
            new_name='name',
        ),
    ]
