# Generated by Django 5.2.1 on 2025-07-03 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youth_policy', '0050_rename_정책명_youthpolicy_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youthpolicy',
            old_name='name',
            new_name='정책명',
        ),
        migrations.RenameField(
            model_name='youthpolicy',
            old_name='document',
            new_name='제출서류내용',
        ),
    ]
