# Generated by Django 5.2.1 on 2025-06-05 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_comment_content_type_comment_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='object_id',
        ),
    ]
