# Generated by Django 5.2.1 on 2025-06-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('review', '후기'), ('share', '자료공유'), ('free', '잡담')], default='free', max_length=20),
        ),
    ]
