# Generated by Django 5.2.1 on 2025-06-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_commentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_blinded',
            field=models.BooleanField(default=False),
        ),
    ]
