# Generated by Django 5.2.1 on 2025-06-20 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0018_postfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
    ]
