# Generated by Django 5.2.1 on 2025-06-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0019_remove_post_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
