# Generated by Django 5.2.1 on 2025-06-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0021_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_notice',
            field=models.BooleanField(default=False, verbose_name='공지글'),
        ),
    ]
